// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/article.proto

package blogpost

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Content struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Content) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type Article struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{1}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Article) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Article) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Article) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Article) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CreateArticleRequest struct {
	Content              *Content `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleRequest) Reset()         { *m = CreateArticleRequest{} }
func (m *CreateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArticleRequest) ProtoMessage()    {}
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{2}
}

func (m *CreateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleRequest.Unmarshal(m, b)
}
func (m *CreateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleRequest.Marshal(b, m, deterministic)
}
func (m *CreateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleRequest.Merge(m, src)
}
func (m *CreateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArticleRequest.Size(m)
}
func (m *CreateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleRequest proto.InternalMessageInfo

func (m *CreateArticleRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *CreateArticleRequest) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

type UpdateArticleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              *Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateArticleRequest) Reset()         { *m = UpdateArticleRequest{} }
func (m *UpdateArticleRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateArticleRequest) ProtoMessage()    {}
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{3}
}

func (m *UpdateArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateArticleRequest.Unmarshal(m, b)
}
func (m *UpdateArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateArticleRequest.Marshal(b, m, deterministic)
}
func (m *UpdateArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateArticleRequest.Merge(m, src)
}
func (m *UpdateArticleRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateArticleRequest.Size(m)
}
func (m *UpdateArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateArticleRequest proto.InternalMessageInfo

func (m *UpdateArticleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateArticleRequest) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type DeleteArticleRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArticleRequest) Reset()         { *m = DeleteArticleRequest{} }
func (m *DeleteArticleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteArticleRequest) ProtoMessage()    {}
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{4}
}

func (m *DeleteArticleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArticleRequest.Unmarshal(m, b)
}
func (m *DeleteArticleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArticleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteArticleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArticleRequest.Merge(m, src)
}
func (m *DeleteArticleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteArticleRequest.Size(m)
}
func (m *DeleteArticleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArticleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArticleRequest proto.InternalMessageInfo

func (m *DeleteArticleRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetArticleListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleListRequest) Reset()         { *m = GetArticleListRequest{} }
func (m *GetArticleListRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleListRequest) ProtoMessage()    {}
func (*GetArticleListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{5}
}

func (m *GetArticleListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListRequest.Unmarshal(m, b)
}
func (m *GetArticleListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListRequest.Merge(m, src)
}
func (m *GetArticleListRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleListRequest.Size(m)
}
func (m *GetArticleListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListRequest proto.InternalMessageInfo

func (m *GetArticleListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetArticleListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetArticleListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetArticleListResponse struct {
	Articles             []*Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetArticleListResponse) Reset()         { *m = GetArticleListResponse{} }
func (m *GetArticleListResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleListResponse) ProtoMessage()    {}
func (*GetArticleListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{6}
}

func (m *GetArticleListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleListResponse.Unmarshal(m, b)
}
func (m *GetArticleListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleListResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleListResponse.Merge(m, src)
}
func (m *GetArticleListResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleListResponse.Size(m)
}
func (m *GetArticleListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleListResponse proto.InternalMessageInfo

func (m *GetArticleListResponse) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type GetArticleByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByIDRequest) Reset()         { *m = GetArticleByIDRequest{} }
func (m *GetArticleByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIDRequest) ProtoMessage()    {}
func (*GetArticleByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{7}
}

func (m *GetArticleByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIDRequest.Unmarshal(m, b)
}
func (m *GetArticleByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetArticleByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIDRequest.Merge(m, src)
}
func (m *GetArticleByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIDRequest.Size(m)
}
func (m *GetArticleByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIDRequest proto.InternalMessageInfo

func (m *GetArticleByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetArticleByIDResponse struct {
	Id                   string                         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              *Content                       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author               *GetArticleByIDResponse_Author `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt            string                         `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                         `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetArticleByIDResponse) Reset()         { *m = GetArticleByIDResponse{} }
func (m *GetArticleByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIDResponse) ProtoMessage()    {}
func (*GetArticleByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{8}
}

func (m *GetArticleByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIDResponse.Unmarshal(m, b)
}
func (m *GetArticleByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetArticleByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIDResponse.Merge(m, src)
}
func (m *GetArticleByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIDResponse.Size(m)
}
func (m *GetArticleByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIDResponse proto.InternalMessageInfo

func (m *GetArticleByIDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetArticleByIDResponse) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GetArticleByIDResponse) GetAuthor() *GetArticleByIDResponse_Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *GetArticleByIDResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetArticleByIDResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetArticleByIDResponse_Author struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename           string   `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	Fullname             string   `protobuf:"bytes,5,opt,name=fullname,proto3" json:"fullname,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByIDResponse_Author) Reset()         { *m = GetArticleByIDResponse_Author{} }
func (m *GetArticleByIDResponse_Author) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIDResponse_Author) ProtoMessage()    {}
func (*GetArticleByIDResponse_Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4830c65b9b5d762, []int{8, 0}
}

func (m *GetArticleByIDResponse_Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIDResponse_Author.Unmarshal(m, b)
}
func (m *GetArticleByIDResponse_Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIDResponse_Author.Marshal(b, m, deterministic)
}
func (m *GetArticleByIDResponse_Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIDResponse_Author.Merge(m, src)
}
func (m *GetArticleByIDResponse_Author) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIDResponse_Author.Size(m)
}
func (m *GetArticleByIDResponse_Author) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIDResponse_Author.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIDResponse_Author proto.InternalMessageInfo

func (m *GetArticleByIDResponse_Author) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetArticleByIDResponse_Author) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *GetArticleByIDResponse_Author) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *GetArticleByIDResponse_Author) GetMiddlename() string {
	if m != nil {
		return m.Middlename
	}
	return ""
}

func (m *GetArticleByIDResponse_Author) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *GetArticleByIDResponse_Author) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetArticleByIDResponse_Author) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Content)(nil), "Content")
	proto.RegisterType((*Article)(nil), "Article")
	proto.RegisterType((*CreateArticleRequest)(nil), "CreateArticleRequest")
	proto.RegisterType((*UpdateArticleRequest)(nil), "UpdateArticleRequest")
	proto.RegisterType((*DeleteArticleRequest)(nil), "DeleteArticleRequest")
	proto.RegisterType((*GetArticleListRequest)(nil), "GetArticleListRequest")
	proto.RegisterType((*GetArticleListResponse)(nil), "GetArticleListResponse")
	proto.RegisterType((*GetArticleByIDRequest)(nil), "GetArticleByIDRequest")
	proto.RegisterType((*GetArticleByIDResponse)(nil), "GetArticleByIDResponse")
	proto.RegisterType((*GetArticleByIDResponse_Author)(nil), "GetArticleByIDResponse.Author")
}

func init() { proto.RegisterFile("protos/article.proto", fileDescriptor_b4830c65b9b5d762) }

var fileDescriptor_b4830c65b9b5d762 = []byte{
	// 537 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0xf4, 0x23, 0x6d, 0xef, 0x6a, 0x1f, 0xc6, 0xb6, 0x1b, 0xa2, 0x2e, 0xcb, 0x20, 0xea,
	0xd3, 0x2c, 0x74, 0xc1, 0x47, 0xa1, 0xed, 0x8a, 0x54, 0x7c, 0x58, 0x22, 0x22, 0x08, 0xb2, 0xa4,
	0x99, 0x69, 0x77, 0x20, 0xc9, 0xc4, 0xcc, 0x54, 0xe8, 0xcf, 0xf0, 0xcd, 0x1f, 0x25, 0xf8, 0x97,
	0xa4, 0x33, 0x93, 0x9a, 0xc4, 0xf8, 0xc1, 0xee, 0x5b, 0xef, 0x3d, 0xf7, 0x9e, 0x7b, 0x6e, 0xe6,
	0xdc, 0xc2, 0x28, 0xcb, 0x85, 0x12, 0xf2, 0x3c, 0xcc, 0x15, 0x8f, 0x62, 0x46, 0x74, 0xe8, 0x3f,
	0xb0, 0xd9, 0x48, 0x24, 0x89, 0x48, 0x4d, 0x12, 0x5f, 0x40, 0x6f, 0x21, 0x52, 0xc5, 0x52, 0x85,
	0x46, 0xd0, 0x55, 0x5c, 0xc5, 0xcc, 0x73, 0xce, 0x9c, 0xe7, 0x83, 0xc0, 0x04, 0x08, 0x41, 0x67,
	0x25, 0xe8, 0xce, 0x6b, 0xe9, 0xa4, 0xfe, 0x8d, 0xbf, 0x39, 0xd0, 0x9b, 0x19, 0x6e, 0x34, 0x84,
	0x16, 0xa7, 0xb6, 0xa5, 0xc5, 0x29, 0xc2, 0xd0, 0x8b, 0x0c, 0xa1, 0x6e, 0x39, 0x9e, 0xf6, 0x89,
	0x1d, 0x10, 0x14, 0x00, 0x7a, 0x08, 0x83, 0x70, 0xab, 0x6e, 0x44, 0x7e, 0xcd, 0xa9, 0xd7, 0xd6,
	0xad, 0x7d, 0x93, 0x58, 0x52, 0xf4, 0x18, 0x20, 0xca, 0x59, 0xa8, 0x18, 0xbd, 0x0e, 0x95, 0xd7,
	0xd1, 0xe8, 0xc0, 0x66, 0x66, 0x6a, 0x0f, 0x6f, 0x33, 0x5a, 0xc0, 0x5d, 0x03, 0xdb, 0xcc, 0x4c,
	0xe1, 0x0f, 0x30, 0x5a, 0xe8, 0x5a, 0xab, 0x2f, 0x60, 0x9f, 0xb7, 0x4c, 0xaa, 0xb2, 0x2c, 0xe7,
	0xbf, 0x64, 0xb5, 0xaa, 0xb2, 0xf0, 0x1b, 0x18, 0xbd, 0xd7, 0x53, 0x6a, 0xc4, 0xb7, 0xd8, 0x1f,
	0x3f, 0x85, 0xd1, 0x25, 0x8b, 0xd9, 0xbf, 0xb8, 0xf0, 0x27, 0x18, 0xbf, 0x66, 0xca, 0x16, 0xbd,
	0xe5, 0x52, 0x15, 0x85, 0x13, 0x70, 0xc5, 0x7a, 0x2d, 0x99, 0x59, 0xa6, 0x1b, 0xd8, 0x68, 0xff,
	0x84, 0x31, 0x4f, 0xb8, 0x19, 0xdd, 0x0d, 0x4c, 0xb0, 0xaf, 0x96, 0x2c, 0xcc, 0xa3, 0x1b, 0xfb,
	0xad, 0x6d, 0x84, 0x5f, 0xc2, 0xa4, 0x4e, 0x2f, 0x33, 0x91, 0x4a, 0x86, 0x9e, 0x40, 0xdf, 0x7a,
	0x47, 0x7a, 0xce, 0x59, 0x5b, 0x6f, 0x51, 0x68, 0x3d, 0x20, 0xf8, 0x59, 0x59, 0xde, 0x7c, 0xb7,
	0xbc, 0xfc, 0xd3, 0x1e, 0x5f, 0xdb, 0xe5, 0x49, 0xa6, 0xd2, 0x4e, 0xba, 0x8d, 0x7d, 0x5e, 0x80,
	0x6b, 0x9e, 0x45, 0xef, 0x73, 0x3c, 0x3d, 0x25, 0xcd, 0xe4, 0x64, 0xa6, 0xab, 0x02, 0x5b, 0x7d,
	0x37, 0x67, 0xf9, 0xdf, 0x1d, 0x70, 0x0d, 0xe1, 0x6f, 0xa2, 0x1f, 0xc1, 0x60, 0xcd, 0x73, 0xa9,
	0xd2, 0x30, 0x61, 0xd6, 0x38, 0xbf, 0x12, 0xc8, 0x87, 0x7e, 0x1c, 0x5a, 0xd0, 0x9a, 0xbd, 0x88,
	0xd1, 0x29, 0x40, 0xc2, 0x29, 0x8d, 0x99, 0x46, 0x8d, 0xa4, 0x52, 0x66, 0xdf, 0xbb, 0xde, 0xc6,
	0xb1, 0x46, 0x8d, 0xa2, 0x43, 0x5c, 0x5b, 0xc7, 0xfd, 0xfb, 0x3a, 0xbd, 0xda, 0x3a, 0xd3, 0x1f,
	0x2d, 0x18, 0xda, 0x6f, 0xf6, 0x8e, 0xe5, 0x5f, 0x78, 0xc4, 0xd0, 0x09, 0x74, 0xae, 0x78, 0xba,
	0x41, 0x2e, 0x79, 0x95, 0x64, 0x6a, 0xe7, 0x77, 0xc9, 0x95, 0x48, 0x37, 0xf8, 0x08, 0x4d, 0xe1,
	0x7e, 0xe5, 0xa8, 0xd0, 0x98, 0x34, 0x1d, 0x99, 0x7f, 0x30, 0x89, 0xe9, 0xa9, 0xdc, 0x0b, 0x1a,
	0x93, 0xa6, 0xfb, 0xa9, 0xf7, 0x54, 0xee, 0x02, 0x8d, 0x49, 0xd3, 0x9d, 0x54, 0x7a, 0x16, 0x30,
	0xac, 0x9a, 0x18, 0x4d, 0x48, 0xe3, 0xd1, 0xf8, 0x27, 0xa4, 0xd9, 0xed, 0x75, 0x92, 0xf9, 0x6e,
	0x49, 0x2b, 0x24, 0x25, 0x6b, 0x57, 0x48, 0xca, 0x5e, 0xc3, 0x47, 0xf3, 0x7b, 0x1f, 0x81, 0x9c,
	0xaf, 0x62, 0xb1, 0xc9, 0x84, 0x54, 0x2b, 0x57, 0xff, 0xbf, 0x5e, 0xfc, 0x0c, 0x00, 0x00, 0xff,
	0xff, 0x56, 0x53, 0xb8, 0xdf, 0x8c, 0x05, 0x00, 0x00,
}
