// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/author.proto

package blogpost

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Author struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string               `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string               `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename           string               `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	Fullname             string               `protobuf:"bytes,5,opt,name=fullname,proto3" json:"fullname,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{0}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Author) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Author) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Author) GetMiddlename() string {
	if m != nil {
		return m.Middlename
	}
	return ""
}

func (m *Author) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *Author) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Author) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Author) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type CreateAuthorRequest struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename           string   `protobuf:"bytes,3,opt,name=middlename,proto3" json:"middlename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAuthorRequest) Reset()         { *m = CreateAuthorRequest{} }
func (m *CreateAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAuthorRequest) ProtoMessage()    {}
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{1}
}

func (m *CreateAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAuthorRequest.Unmarshal(m, b)
}
func (m *CreateAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAuthorRequest.Marshal(b, m, deterministic)
}
func (m *CreateAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAuthorRequest.Merge(m, src)
}
func (m *CreateAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAuthorRequest.Size(m)
}
func (m *CreateAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAuthorRequest proto.InternalMessageInfo

func (m *CreateAuthorRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *CreateAuthorRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *CreateAuthorRequest) GetMiddlename() string {
	if m != nil {
		return m.Middlename
	}
	return ""
}

type UpdateAuthorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename           string   `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAuthorRequest) Reset()         { *m = UpdateAuthorRequest{} }
func (m *UpdateAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAuthorRequest) ProtoMessage()    {}
func (*UpdateAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{2}
}

func (m *UpdateAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAuthorRequest.Unmarshal(m, b)
}
func (m *UpdateAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAuthorRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAuthorRequest.Merge(m, src)
}
func (m *UpdateAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAuthorRequest.Size(m)
}
func (m *UpdateAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAuthorRequest proto.InternalMessageInfo

func (m *UpdateAuthorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAuthorRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UpdateAuthorRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *UpdateAuthorRequest) GetMiddlename() string {
	if m != nil {
		return m.Middlename
	}
	return ""
}

type DeleteAuthorRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthorRequest) Reset()         { *m = DeleteAuthorRequest{} }
func (m *DeleteAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthorRequest) ProtoMessage()    {}
func (*DeleteAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{3}
}

func (m *DeleteAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthorRequest.Unmarshal(m, b)
}
func (m *DeleteAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthorRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthorRequest.Merge(m, src)
}
func (m *DeleteAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthorRequest.Size(m)
}
func (m *DeleteAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthorRequest proto.InternalMessageInfo

func (m *DeleteAuthorRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAuthorListRequest struct {
	Offset               int32    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorListRequest) Reset()         { *m = GetAuthorListRequest{} }
func (m *GetAuthorListRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorListRequest) ProtoMessage()    {}
func (*GetAuthorListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{4}
}

func (m *GetAuthorListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorListRequest.Unmarshal(m, b)
}
func (m *GetAuthorListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorListRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorListRequest.Merge(m, src)
}
func (m *GetAuthorListRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorListRequest.Size(m)
}
func (m *GetAuthorListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorListRequest proto.InternalMessageInfo

func (m *GetAuthorListRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetAuthorListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAuthorListRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetAuthorListResponse struct {
	Authors              []*Author `protobuf:"bytes,1,rep,name=Authors,proto3" json:"Authors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAuthorListResponse) Reset()         { *m = GetAuthorListResponse{} }
func (m *GetAuthorListResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorListResponse) ProtoMessage()    {}
func (*GetAuthorListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{5}
}

func (m *GetAuthorListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorListResponse.Unmarshal(m, b)
}
func (m *GetAuthorListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorListResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorListResponse.Merge(m, src)
}
func (m *GetAuthorListResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorListResponse.Size(m)
}
func (m *GetAuthorListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorListResponse proto.InternalMessageInfo

func (m *GetAuthorListResponse) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

type GetAuthorByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorByIDRequest) Reset()         { *m = GetAuthorByIDRequest{} }
func (m *GetAuthorByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorByIDRequest) ProtoMessage()    {}
func (*GetAuthorByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{6}
}

func (m *GetAuthorByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorByIDRequest.Unmarshal(m, b)
}
func (m *GetAuthorByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorByIDRequest.Merge(m, src)
}
func (m *GetAuthorByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorByIDRequest.Size(m)
}
func (m *GetAuthorByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorByIDRequest proto.InternalMessageInfo

func (m *GetAuthorByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAuthorByIDResponse struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string               `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string               `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Middlename           string               `protobuf:"bytes,4,opt,name=middlename,proto3" json:"middlename,omitempty"`
	Fullname             string               `protobuf:"bytes,5,opt,name=fullname,proto3" json:"fullname,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetAuthorByIDResponse) Reset()         { *m = GetAuthorByIDResponse{} }
func (m *GetAuthorByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorByIDResponse) ProtoMessage()    {}
func (*GetAuthorByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3958f4382bb72a, []int{7}
}

func (m *GetAuthorByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorByIDResponse.Unmarshal(m, b)
}
func (m *GetAuthorByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorByIDResponse.Merge(m, src)
}
func (m *GetAuthorByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorByIDResponse.Size(m)
}
func (m *GetAuthorByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorByIDResponse proto.InternalMessageInfo

func (m *GetAuthorByIDResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetAuthorByIDResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *GetAuthorByIDResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *GetAuthorByIDResponse) GetMiddlename() string {
	if m != nil {
		return m.Middlename
	}
	return ""
}

func (m *GetAuthorByIDResponse) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *GetAuthorByIDResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetAuthorByIDResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *GetAuthorByIDResponse) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Author)(nil), "Author")
	proto.RegisterType((*CreateAuthorRequest)(nil), "CreateAuthorRequest")
	proto.RegisterType((*UpdateAuthorRequest)(nil), "UpdateAuthorRequest")
	proto.RegisterType((*DeleteAuthorRequest)(nil), "DeleteAuthorRequest")
	proto.RegisterType((*GetAuthorListRequest)(nil), "GetAuthorListRequest")
	proto.RegisterType((*GetAuthorListResponse)(nil), "GetAuthorListResponse")
	proto.RegisterType((*GetAuthorByIDRequest)(nil), "GetAuthorByIDRequest")
	proto.RegisterType((*GetAuthorByIDResponse)(nil), "GetAuthorByIDResponse")
}

func init() { proto.RegisterFile("protos/author.proto", fileDescriptor_cc3958f4382bb72a) }

var fileDescriptor_cc3958f4382bb72a = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0xdd, 0xda, 0x69, 0xa6, 0x2d, 0x87, 0x8d, 0x5b, 0x22, 0x0b, 0x41, 0x58, 0x09, 0x94,
	0xd3, 0x5a, 0x84, 0x13, 0x9c, 0x48, 0x28, 0x42, 0x95, 0x38, 0x54, 0x06, 0x2e, 0x08, 0x09, 0x39,
	0xf1, 0xda, 0x5d, 0xc9, 0xf6, 0x1a, 0xef, 0x1a, 0x29, 0x27, 0x7e, 0x89, 0x3f, 0xe0, 0x0f, 0xf8,
	0x26, 0x94, 0xdd, 0x35, 0x6c, 0x22, 0x93, 0x4a, 0x1c, 0x38, 0x71, 0x9c, 0x99, 0xf7, 0x76, 0xde,
	0xbc, 0x9d, 0x81, 0x51, 0xdd, 0x70, 0xc9, 0x45, 0x94, 0xb4, 0xf2, 0x86, 0x37, 0x44, 0x45, 0x61,
	0x97, 0x5c, 0xf1, 0xb2, 0xe4, 0x95, 0x49, 0x3e, 0xc8, 0x39, 0xcf, 0x0b, 0x1a, 0xa9, 0x68, 0xd9,
	0x66, 0x91, 0x64, 0x25, 0x15, 0x32, 0x29, 0x6b, 0x0d, 0xc0, 0xdf, 0x5d, 0xf0, 0xe7, 0xea, 0x19,
	0x74, 0x07, 0x5c, 0x96, 0x8e, 0x9d, 0x89, 0x33, 0x1d, 0xc6, 0x2e, 0x4b, 0xd1, 0x3d, 0x18, 0x66,
	0xac, 0x11, 0xb2, 0x4a, 0x4a, 0x3a, 0x76, 0x55, 0xfa, 0x77, 0x02, 0x85, 0x70, 0x5c, 0x24, 0xa6,
	0x78, 0xa8, 0x8a, 0xbf, 0x62, 0x74, 0x1f, 0xa0, 0x64, 0x69, 0x5a, 0x50, 0x55, 0x3d, 0x52, 0x55,
	0x2b, 0xb3, 0xe1, 0x66, 0x6d, 0x51, 0xa8, 0xaa, 0xa7, 0xb9, 0x5d, 0x8c, 0x9e, 0x01, 0xac, 0x1a,
	0x9a, 0x48, 0x9a, 0x7e, 0x4a, 0xe4, 0xd8, 0x9f, 0x38, 0xd3, 0x93, 0x59, 0x48, 0xf4, 0x18, 0xa4,
	0x1b, 0x83, 0xbc, 0xeb, 0xc6, 0x88, 0x87, 0x06, 0x3d, 0x97, 0x1b, 0x6a, 0x5b, 0xa7, 0x1d, 0x75,
	0x70, 0x3b, 0xd5, 0xa0, 0x35, 0x35, 0xa5, 0x05, 0x35, 0xd4, 0xe3, 0xdb, 0xa9, 0x06, 0x3d, 0x97,
	0x98, 0xc3, 0xe8, 0xa5, 0x92, 0xa0, 0x6d, 0x8c, 0xe9, 0xe7, 0x96, 0x0a, 0xb9, 0xed, 0x9e, 0xb3,
	0xcf, 0x3d, 0x77, 0xaf, 0x7b, 0x87, 0xbb, 0xee, 0xe1, 0xaf, 0x30, 0x7a, 0xaf, 0x84, 0x6f, 0x37,
	0xfc, 0x67, 0xdf, 0x87, 0x1f, 0xc1, 0xe8, 0x52, 0x8d, 0xbf, 0x57, 0x00, 0xfe, 0x08, 0xc1, 0x6b,
	0x2a, 0x35, 0xe6, 0x0d, 0x13, 0xb2, 0xc3, 0x5d, 0x80, 0xcf, 0xb3, 0x4c, 0x50, 0xa9, 0xb0, 0x5e,
	0x6c, 0x22, 0x14, 0x80, 0x57, 0xb0, 0x92, 0x49, 0x25, 0xd6, 0x8b, 0x75, 0xb0, 0x41, 0x0b, 0x9a,
	0x34, 0xab, 0x1b, 0x23, 0xd3, 0x44, 0xf8, 0x39, 0x9c, 0xef, 0xbc, 0x2e, 0x6a, 0x5e, 0x09, 0x8a,
	0x1e, 0xc2, 0x40, 0x67, 0xc5, 0xd8, 0x99, 0x1c, 0x4e, 0x4f, 0x66, 0x03, 0x62, 0x74, 0x76, 0x79,
	0xfc, 0xd8, 0x52, 0xb6, 0x58, 0x5f, 0x5d, 0xfe, 0x69, 0x82, 0x1f, 0xae, 0xd5, 0x44, 0x03, 0x4d,
	0x93, 0xff, 0xb7, 0xf2, 0x37, 0xb7, 0x32, 0xfb, 0xe6, 0xc2, 0x99, 0x76, 0xf3, 0x2d, 0x6d, 0xbe,
	0xb0, 0x15, 0x45, 0x77, 0xe1, 0xe8, 0x9a, 0x55, 0x39, 0xf2, 0xc9, 0xab, 0xb2, 0x96, 0xeb, 0xd0,
	0x23, 0xd7, 0xbc, 0xca, 0xf1, 0x01, 0x8a, 0xe0, 0xd4, 0x3e, 0x2b, 0x14, 0x90, 0x9e, 0x2b, 0x0b,
	0xbb, 0xbf, 0xd5, 0x04, 0xfb, 0x2c, 0x50, 0x40, 0x7a, 0xae, 0x64, 0x87, 0x60, 0xaf, 0x31, 0x0a,
	0x48, 0xcf, 0x56, 0xdb, 0x84, 0x17, 0x70, 0xb6, 0xb5, 0x72, 0xe8, 0x9c, 0xf4, 0x2d, 0x78, 0x78,
	0x41, 0x7a, 0x37, 0x13, 0x1f, 0xa0, 0x27, 0xd6, 0x0b, 0x8b, 0xf5, 0x55, 0x6a, 0xbf, 0x60, 0x2d,
	0xa2, 0xd5, 0x74, 0x71, 0xfa, 0x01, 0x48, 0xb4, 0x2c, 0x78, 0x5e, 0x73, 0x21, 0x97, 0xbe, 0xf2,
	0xf7, 0xe9, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xa2, 0xd5, 0xd7, 0x02, 0x06, 0x00, 0x00,
}
